### ISSUE TITLE
installation distante

### ISSUE THREAD

**Issue by jamll** [marsante/MedShakeEHR-docker-compose#1]
Bonjour j'essaye d'installer la stack MEDSHAKE sur un serveur distant malgré les différentes configurations du paramètre virtual_host dans le compose j'ai toujours cette erreur :
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 192.168.32.2. Set the 'ServerName' directive globally to suppress this message

nb merci pour le travail accompli

**Comment by marsante** [comment]
Bonjour Jamll,

Merci pour votre message.

C' est une alerte sans grande importance. Comme le servername.conf n'est pas configuré dans le conteneur il avertit. Il prend quand même l'IP par défaut. Si vous arrivez à contacter la page d'accueil tout va bien. Vous pouvez regarder cette solution si vous voulez quand même faire disparaitre le message https://stackoverflow.com/questions/46266527/ah00558-apache2-could-not-reliably-determine-the-servers-fully-qualified-doma

Si vous n'arrivez pas à afficher la page d'accueil il faut creuser d'autres messages, tenez moi au courant.

Prenez soin de vous,

**Comment by jamll** [comment]
bonjour 

Merci pour la réponse rapide 
sur docker desktop en config locale j'ai bien la page d'acceuil pour configurer la db
puis je tombe sur cette erreur 

> Fatal error: Uncaught PDOException: SQLSTATE[HY000] [1045] Access denied for user ''@'172.22.0.2' (using password: NO) in /var/www/html/class/msSQL.php:43 Stack trace: #0 /var/www/html/class/msSQL.php(43): PDO->__construct() #1 /var/www/html/public_html/install.php(177): msSQL::sqlConnect() #2 {main} thrown in /var/www/html/class/msSQL.php on line 43

en distant je n'ai pas d'accès si je change msehr.local par mon ip ou l'ip locale de la VM meme en ajoutant les ports dans le paramètre  virtual host

prenez soin de vous également



`

**Comment by marsante** [comment]
> sur docker desktop en config locale j'ai bien la page d'acceuil pour configurer la db
puis je tombe sur cette erreur

    Fatal error: Uncaught PDOException: SQLSTATE[HY000] [1045] Access denied for user ''@'172.22.0.2' (using password: NO) in /var/www/html/class/msSQL.php:43 Stack trace: #0 /var/www/html/class/msSQL.php(43): PDO->__construct() https://github.com/marsante/MedShakeEHR-docker-compose/issues/1 /var/www/html/public_html/install.php(177): msSQL::sqlConnect() #2 {main} thrown in /var/www/html/class/msSQL.php on line 43

Je viens de tester sur Windows 10 (ça faisait longtemps), je n'ai pas d'erreur. Est-ce que vous pouvez copier votre docker-compose.yml, peut-être utilisez-vous une ancienne image ?

> en distant je n'ai pas d'accès si je change msehr.local par mon ip ou l'ip locale de la VM meme en ajoutant les ports dans le paramètre virtual host 

Je n'ai pas testé sur Windows l'accès au réseau local, mais il faudrait probablement regarder déjà si le parefeu windows ne bloque pas ?

prenez soin de vous,

**Comment by jamll** [comment]
Désolé en fait je n'ai pas précisé ma config de test 
-Locale sur windows avec docker desktop et un portainer local 
mais maintenant j'ai un pb  msehr.localhost me renvoie vers xampp du coup conflit malgré un changement de port sur docker (peut être faut'il changer les ports sur xampp pas encore testé...)

-Distante sur serveur dédié OVH proxmox dans une VM debian 12 (toujours avec docker et portainer)
j'ai déjà réussi une install baremetal et une install dans une VM debian 12 (que je teste actuellement)
mais je voudrais trouver les bonnes configs pour le docker compose car j'aime bien l'aspect tout en un avec le VPN intégré
et la rapidité de l'installation en cas de pb

ci-joint les docker compose
[docker-compose-distant.yml.txt](https://github.com/marsante/MedShakeEHR-docker-compose/files/12806122/docker-compose-distant.yml.txt)
[docker-compose-local.yml.txt](https://github.com/marsante/MedShakeEHR-docker-compose/files/12806123/docker-compose-local.yml.txt)

**Comment by jamll** [comment]
et encore merci pou l'aide

**Comment by marsante** [comment]
Essayez avec le tag 8.0.3 pour le souci de pdoexception. Je n'ai pas eu le temps de générer l'image 8.0.4 depuis mon retour, vous pourrez la mettre à jour avec la méthode classique du zip.

> mais maintenant j'ai un pb msehr.localhost me renvoie vers xampp

Je ne gère pas ce cas d'usage, peut-être couper xamp ou changer les ports en effet.

> Distante sur serveur dédié OVH proxmox dans une VM debian 12 (toujours avec docker et portainer)
j'ai déjà réussi une install baremetal et une install dans une VM debian 12 (que je teste actuellement)

MedShakeEHR n'est pas conçu pour être exposé sur le web, attention à bien configurer le pare-feu et le vpn.

Chez OVH, il faut faire attention, tous les produits ne sont pas HDS, une page récapitule la chose : https://www.ovhcloud.com/fr/enterprise/certification-conformity/hds/

Pour le vpn https://hub.docker.com/r/linuxserver/wireguard est plutôt simple à mettre en place.

Pensez aussi à chiffrer votre disque, les disques des hébergeurs ne le sont pas forcément comme le montre cette vidéo https://www.youtube.com/watch?v=E6hDSPusGfE et peuvent se retrouver dans la nature.

La dockerisation de medshakeehr est encore expérimentale, il reste plus simple de l'installer dans une VM (vous pouvez utiliser mon playbook ansible pour mettre en place le tout avec le vpn). Vous pouvez également regarder la pull request de bugeaud sur le projet principal qui a fait un gros travail pour dockeriser le logiciel. Son implémentation ne fonctionnera pas en local sur Windows, mais devrait fonctionner sur Linux. De mon côté, il faut que j'arrive à faire un script qui permette d'alerter des mises à jour.

**Comment by jamll** [comment]
Super merci pour toutes ces explications très détaillées 
j’appréhende mieux l'installation de MedShake maintenant ...
je fais juste des tests car je dispose d'un serveur dell R440 poweredge au cabinet sous proxmox 8/debian12 mais encore un petit pb de connexion à distance avec la livebox pro en cours de traitement.

Du coup je vais créer une VM pour tester le déploiement ansible sur vos conseils et j'utiliserais une infra plus sécurisée pour ce serveur perso avec chiffrement des disques et des connexion par SSL sur domaine perso et VPN.
mais j'avais besoin de me familiariser avec le logiciel ...

je surveillerais attentivement les modification/améliorations des repos évoqués
j'espère avoir un système fonctionnel et stable dans les 6 mois  au moins pour l'édition de documents
(avec apicrypt et vitaonline également fonctionnels si possible)


Encore merci

**Comment by marsante** [comment]
Parfait. N'hésitez pas si vous avez besoin d'aide. Et pour docker, vous pouvez également l'utiliser si vos tests sont concluants.
Est-ce que la version 8.0.3 résout l'erreur  ?

> Fatal error: Uncaught PDOException: SQLSTATE[HY000] [1045] Access denied for user ''@'172.22.0.2' (using password: NO) in /var/www/html/class/msSQL.php:43 Stack trace: #0 /var/www/html/class/msSQL.php(43): PDO->__construct() https://github.com/marsante/MedShakeEHR-docker-compose/issues/1 /var/www/html/public_html/install.php(177): msSQL::sqlConnect() #2 {main} thrown in /var/www/html/class/msSQL.php on line 43

Prenez soin de vous,
